config/routes.rb
Rails.application.routes.draw do
  resources :contact_forms, only: [:new, :create]
  get 'contact_forms/new'
  get 'contact_forms/create'
  # get "contact", to:'contact#index'
  get "resume", to:'resume#index'
  get "home", to: 'home#index'
  get "projects", to:'project#index'
  get '/descargar/archivo', to: 'downloads#descargar_archivo'
 

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/contact_form.rb
class ContactForm < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    NotificationJob.set(wait: 1.minute).perform_later

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  def new
    @contact_form = ContactForm.new
  end

  def create
    @contact_form = ContactForm.new(contact_form_params)
    if @contact_form.save
      flash[:success] = "¡Mensaje enviado correctamente!"
      redirect_to new_contact_form_path
    else
      render :new
    end
  end

  private

  def contact_form_params
    params.require(:contact_form).permit(:name, :phone, :email, :message)
  end
end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
    def descargar_archivo
        archivo_path = Rails.root.join('public/Mi_Curriculum.pdf')  # Ruta al archivo
        send_file archivo_path
      end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/downloads_helper.rb
module DownloadsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/contact/index.html.erb
 <body class="d-flex flex-column">
        <main class="flex-shrink-0">
          
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <!-- Contact form-->
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                            <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
                            <h1 class="fw-bolder">Get in touch</h1>
                            <p class="lead fw-normal text-muted mb-0">Let's work together!</p>
                        </div>
                        <div class="row gx-5 justify-content-center">
                            <div class="col-lg-8 col-xl-6">
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- * * SB Forms Contact Form * *-->
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- This form is pre-integrated with SB Forms.-->
                                <!-- To make this form functional, sign up at-->
                                <!-- https://startbootstrap.com/solution/contact-forms-->
                                <!-- to get an API token!-->
                                <%= form_with(model: @contact_form, url: contact_forms_path) do |form| %>
                                <%# <form id="contactForm" data-sb-form-api-token="API_TOKEN"> %>
                                    <!-- Name input-->
                                    <div class="form-floating mb-3">
                                        <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                                        <label for="name">Full name</label>
                                        <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                                    </div>
                                    <!-- Email address input-->
                                    <div class="form-floating mb-3">
                                        <input class="form-control" id="email" type="email" placeholder="name@example.com" data-sb-validations="required,email" />
                                        <label for="email">Email address</label>
                                        <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                                        <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                                    </div>
                                    <!-- Phone number input-->
                                    <div class="form-floating mb-3">
                                        <input class="form-control" id="phone" type="tel" placeholder="(123) 456-7890" data-sb-validations="required" />
                                        <label for="phone">Phone number</label>
                                        <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                                    </div>
                                    <!-- Message input-->
                                    <div class="form-floating mb-3">
                                        <textarea class="form-control" id="message" type="text" placeholder="Enter your message here..." style="height: 10rem" data-sb-validations="required"></textarea>
                                        <label for="message">Message</label>
                                        <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                                    </div>
                                    <!-- Submit success message-->
                                    <!---->
                                    <!-- This is what your users will see when the form-->
                                    <!-- has successfully submitted-->
                                    <div class="d-none" id="submitSuccessMessage">
                                        <div class="text-center mb-3">
                                            <div class="fw-bolder">Form submission successful!</div>
                                            To activate this form, sign up at
                                            <br />
                                            <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                        </div>
                                    </div>
                                    <!-- Submit error message-->
                                    <!---->
                                    <!-- This is what your users will see when there is-->
                                    <!-- an error submitting the form-->
                                    <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                                    <!-- Submit Button-->
                                    <div class="d-grid"><button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Submit</button></div>
                                <% end%>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </main>

app/views/contact_forms/create.html.erb
<h1>ContactForms#create</h1>
<p>Find me in app/views/contact_forms/create.html.erb</p>

app/views/contact_forms/new.html.erb
 <body class="d-flex flex-column">
        <main class="flex-shrink-0">
          
            <!-- Page content-->
            <section class="py-5">
                <div class="container px-5">
                    <!-- Contact form-->
                    <div class="bg-light rounded-4 py-5 px-4 px-md-5">
                        <div class="text-center mb-5">
                            <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
                            <h1 class="fw-bolder">Get in touch</h1>
                            <p class="lead fw-normal text-muted mb-0">Let's work together!</p>
                        </div>
                        <div class="row gx-5 justify-content-center">
                            <div class="col-lg-8 col-xl-6">
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- * * SB Forms Contact Form * *-->
                                <!-- * * * * * * * * * * * * * * *-->
                                <!-- This form is pre-integrated with SB Forms.-->
                                <!-- To make this form functional, sign up at-->
                                <!-- https://startbootstrap.com/solution/contact-forms-->
                                <!-- to get an API token!-->
                                <%= form_with model: @contact_form, id: "contact-form" do |form| %>
  <!-- Name input -->
  <div class="form-floating mb-3">
    <%= form.text_field :name, class: "form-control", id: "name", placeholder: "Enter your name..." %>
    <%= form.label :name, "Full name" %>
    <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
  </div>
  
  <!-- Email address input -->
  <div class="form-floating mb-3">
    <%= form.email_field :email, class: "form-control", id: "email", placeholder: "name@example.com" %>
    <%= form.label :email, "Email address" %>
    <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
    <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
  </div>
  
  <!-- Phone number input -->
  <div class="form-floating mb-3">
    <%= form.phone_field :phone, class: "form-control", id: "phone", placeholder: "(123) 456-7890" %>
    <%= form.label :phone, "Phone number" %>
    <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
  </div>
  
  <!-- Message input -->
  <div class="form-floating mb-3">
    <%= form.text_area :message, class: "form-control", id: "message", placeholder: "Enter your message here...", style: "height: 10rem" %>
    <%= form.label :message, "Message" %>
    <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
  </div>
  
  <!-- Submit Button -->
  <div class="d-grid">
    <%= form.submit "Submit", class: "btn btn-primary btn-lg", id: "submitButton" %>
  </div>
<% end %>

<!-- Submit success message -->
<div class="d-none" id="submitSuccessMessage">
  <div class="text-center mb-3">
    <div class="fw-bolder">Form submission successful!</div>
    To activate this form, sign up at
    <br />
    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
  </div>
</div>

<!-- Submit error message -->
<div class="d-none" id="submitErrorMessage">
  <div class="text-center text-danger mb-3">Error sending message!</div>
</div>

            <% if flash[:success] %>
  <div class="alert alert-success">
    <%= flash[:success] %>
  </div>
<% end %>
        </main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adrian Ramos · Developer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
     <!-- Core theme JS-->
    <%= javascript_importmap_tags "scripts" %>

    <!-- Favicon-->
     <%= favicon_link_tag 'logo_vectorial.png', type:"image/x-icon" %>
        <!-- Custom Google font-->
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@100;200;300;400;500;600;700;800;900&amp;display=swap" rel="stylesheet" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css" rel="stylesheet" />
            <script src="https://kit.fontawesome.com/41b8753ddc.js" crossorigin="anonymous"></script>
        <!-- Core theme CSS (includes Bootstrap)-->
         <%= stylesheet_link_tag "styles", "data-turbo-track": "reload" %>

  </head>

  <body>
  <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-white py-3">
                <div class="container px-5">
                    <%= image_tag "logo_vectorial_pequeño", width:"100px", id:"logo_vectorial"%>
                    <%# <br>
                    <a class="navbar-brand" href="index.html"><span class="fw-bolder text-primary">Adrian Marcelo</span></a> %>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 small fw-bolder">
                            <li class="nav-item"><%= link_to 'Home', home_path ,class:"nav-link"%>
                            <li class="nav-item"><%= link_to 'Resume', resume_path ,class:"nav-link"%>
                            <%# <li class="nav-item"><%= link_to 'Projects', projects_path ,class:"nav-link"%>
                            <li class="nav-item"><%= link_to 'Contact', contact_forms_new_path ,class:"nav-link"%>
                        </ul>
                    </div>
                </div>
            </nav>
    <%= yield %>
     <section class="bg-light py-5">
                <div class="container px-5">
                    <div class="row gx-5 justify-content-center">
                        <div class="col-xxl-8">
                                <div class="d-flex justify-content-center fs-2 gap-4">
                                    <a class="text-gradient" href="https://www.instagram.com/adrianramos4504/" target="_blank"><i class="bi bi-instagram"></i></a>
                                    <a class="text-gradient" href="https://www.linkedin.com/in/adrián-ramos-b3869447/" target="_blank"><i class="bi bi-linkedin"></i></a>
                                    <a class="text-gradient" href="https://github.com/AMarceloRamos" target="_blank"><i class="bi bi-github"></i></a>
                                    <a class="text-gradient" href="https://www.deviantart.com/adrian22ya" target="_blank"><i class="fa-brands fa-deviantart"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
    <!-- Footer-->
        <footer class="bg-white py-4 mt-auto">
            <div class="container px-5">
                <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                    <div class="col-auto"><div class="small m-0">Copyright &copy;<span class="text-gradient d-inline"> AdrianRamos2023</span></div></div>
                    <div class="col-auto">
                        <a class="small" href="#!">Privacy</a>
                        <span class="mx-1">&middot;</span>
                        <a class="small" href="#!">Terms</a>
                        <span class="mx-1">&middot;</span>
                        <%= link_to 'Contact', contact_forms_new_path %>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
      
  </body>
</html>

app/views/project/index.html.erb
<body class="d-flex flex-column h-100 bg-light">
        <main class="flex-shrink-0">
           
            <!-- Projects Section-->
            <section class="py-5">
                <div class="container px-5 mb-5">
                    <div class="text-center mb-5">
                        <h1 class="display-5 fw-bolder mb-0"><span class="text-gradient d-inline">Projects</span></h1>
                    </div>
                    <div class="row gx-5 justify-content-center">
                        <div class="col-lg-11 col-xl-9 col-xxl-8">
                            <!-- Project Card 1-->
                            <div class="card overflow-hidden shadow rounded-4 border-0 mb-5">
                                <div class="card-body p-0">
                                    <div class="d-flex align-items-center">
                                        <div class="p-5">
                                            <h2 class="fw-bolder">Project Name 1</h2>
                                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius at enim eum illum aperiam placeat esse? Mollitia omnis minima saepe recusandae libero, iste ad asperiores! Explicabo commodi quo itaque! Ipsam!</p>
                                        </div>
                                        <img class="img-fluid" src="https://dummyimage.com/300x400/343a40/6c757d" alt="..." />
                                    </div>
                                </div>
                            </div>
                            <!-- Project Card 2-->
                            <div class="card overflow-hidden shadow rounded-4 border-0">
                                <div class="card-body p-0">
                                    <div class="d-flex align-items-center">
                                        <div class="p-5">
                                            <h2 class="fw-bolder">Project Name 2</h2>
                                            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eius at enim eum illum aperiam placeat esse? Mollitia omnis minima saepe recusandae libero, iste ad asperiores! Explicabo commodi quo itaque! Ipsam!</p>
                                        </div>
                                        <img class="img-fluid" src="https://dummyimage.com/300x400/343a40/6c757d" alt="..." />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!-- Call to action section-->
            <section class="py-5 bg-gradient-primary-to-secondary text-white">
                <div class="container px-5 my-5">
                    <div class="text-center">
                        <h2 class="display-4 fw-bolder mb-4">Let's build something together</h2>
                        <%= link_to 'Contact me', new_contact_form_path,class:"btn btn-outline-light btn-lg px-5 py-3 fs-6 fw-bolder"%>
                        
                    </div>
                </div>
            </section>
        </main>

app/views/resume/index.html.erb
 <title>Resumen</title>
 <body class="d-flex flex-column h-100 bg-light">
        <main class="flex-shrink-0">

            <!-- Page Content-->
            <div class="container px-5 my-5">
                <div class="text-center mb-5">
                    <h1 class="display-5 fw-bolder mb-0"><span class="text-gradient d-inline">Resume</span></h1>
                </div>
                <div class="row gx-5 justify-content-center">
                    <div class="col-lg-11 col-xl-9 col-xxl-8">
                     
                        <!-- Education Section-->
                        <section>
                            <h2 class="text-secondary fw-bolder mb-4">Education</h2>
                            <!-- Education Card 1-->
                            <div class="card shadow border-0 rounded-4 mb-5">
                                <div class="card-body p-5">
                                    <div class="row align-items-center gx-5">
                                        <div class="col text-center text-lg-start mb-4 mb-lg-0">
                                            <div class="bg-light p-4 rounded-4">
                                                <div class="text-secondary fw-bolder mb-2">2021 - Presente</div>
                                                <div class="mb-2">
                                                    <div class="small fw-bolder">Instituto IACC</div>
                                                    <div class="small text-muted">Santiago</div>
                                                </div>
                                                <div class="fst-italic">
                                                    <div class="small text-muted">Estudiante</div>
                                                    <div class="small text-muted">Técnico en análisis y programación computacional</div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-8"><div>Mis competencias incluyen JavaScript, PHP, Ruby on Rails, HTML, CSS y Bootstrap, lo que me permite ser versátil en el desarrollo de aplicaciones web..</div></div>
                                    </div>
                                </div>
                            </div>
                            <!-- Education Card 2-->
                            <div class="card shadow border-0 rounded-4 mb-5">
                                <div class="card-body p-5">
                                    <div class="row align-items-center gx-5">
                                        <div class="col text-center text-lg-start mb-4 mb-lg-0">
                                            <div class="bg-light p-4 rounded-4">
                                                <div class="text-secondary fw-bolder mb-2">2008-2010</div>
                                                <div class="mb-2">
                                                    <div class="small fw-bolder">Universidad Santo Tomás</div>
                                                    <div class="small text-muted">Santiago, Región Metropolitana</div>
                                                </div>
                                                <div class="fst-italic">
                                                    <div class="small text-muted">Undergraduate</div>
                                                    <div class="small text-muted">Diseño Gráfico</div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-8"><div>Tengo manejo y conocimientos en programas de diseño como los que componene Adobe Software Suite y demás herramientas gráficas.</div></div>
                                    </div>
                                </div>
                            </div>
                        </section>

                           <!-- Experience Section-->
                        <section>
                            <div class="d-flex align-items-center justify-content-between mb-4">
                                <%# <h2 class="text-primary fw-bolder mb-0">Experience</h2> %>
                                <!-- Download resume button-->
                                <!-- Note: Set the link href target to a PDF file within your project-->
                                <%# <a class="btn btn-primary px-4 py-3" href="#!">
                                    <div class="d-inline-block bi bi-download me-2"></div>
                                    Download Resume
                                </a> %>
                                <%= link_to 'Descargar Resumen', '/descargar/archivo', class:" btn btn-primary d-inline-block bi bi-download me-2 " %>

                            </div>
                            <%# <!-- Experience Card 1-->
                            <div class="card shadow border-0 rounded-4 mb-5">
                                <div class="card-body p-5">
                                    <div class="row align-items-center gx-5">
                                        <div class="col text-center text-lg-start mb-4 mb-lg-0">
                                            <div class="bg-light p-4 rounded-4">
                                                <div class="text-primary fw-bolder mb-2">2019 - Present</div>
                                                <div class="small fw-bolder">Web Developer</div>
                                                <div class="small text-muted">Stark Industries</div>
                                                <div class="small text-muted">Los Angeles, CA</div>
                                            </div>
                                        </div>
                                        <div class="col-lg-8"><div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus laudantium, voluptatem quis repellendus eaque sit animi illo ipsam amet officiis corporis sed aliquam non voluptate corrupti excepturi maxime porro fuga.</div></div>
                                    </div>
                                </div>
                            </div>
                            <!-- Experience Card 2-->
                            <div class="card shadow border-0 rounded-4 mb-5">
                                <div class="card-body p-5">
                                    <div class="row align-items-center gx-5">
                                        <div class="col text-center text-lg-start mb-4 mb-lg-0">
                                            <div class="bg-light p-4 rounded-4">
                                                <div class="text-primary fw-bolder mb-2">2017 - 2019</div>
                                                <div class="small fw-bolder">SEM Specialist</div>
                                                <div class="small text-muted">Wayne Enterprises</div>
                                                <div class="small text-muted">Gotham City, NY</div>
                                            </div>
                                        </div>
                                        <div class="col-lg-8"><div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus laudantium, voluptatem quis repellendus eaque sit animi illo ipsam amet officiis corporis sed aliquam non voluptate corrupti excepturi maxime porro fuga.</div></div>
                                    </div>
                                </div> %>
                            </div>
                        </section>
                        <!-- Divider-->
                        <div class="pb-5"></div>
                        <!-- Skills Section-->
                        <section>
                            <!-- Skillset Card-->
                            <div class="card shadow border-0 rounded-4 mb-5">
                                <div class="card-body p-5">
                                    <!-- Professional skills list-->
                                    <div class="mb-5">
                                        <div class="d-flex align-items-center mb-4">
                                            <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 me-3"><i class="bi bi-tools"></i></div>
                                            <h3 class="fw-bolder mb-0"><span class="text-gradient d-inline">Professional Skills</span></h3>
                                        </div>
                                        <div class="row row-cols-1 row-cols-md-3 mb-4">
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">Programación</div></div>
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">Técnico en computación</div></div>
                                            <div class="col"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">Web Development</div></div>
                                        </div>
                                        <div class="row row-cols-1 row-cols-md-3">
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">Network Security</div></div>
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">Adobe Software Suite</div></div>
                                            <div class="col"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">User Interface Design</div></div>
                                        </div>
                                    </div>
                                    <!-- Languages list-->
                                    <div class="mb-0">
                                        <div class="d-flex align-items-center mb-4">
                                            <div class="feature bg-primary bg-gradient-primary-to-secondary text-white rounded-3 me-3"><i class="bi bi-code-slash"></i></div>
                                            <h3 class="fw-bolder mb-0"><span class="text-gradient d-inline">Languages</span></h3>
                                        </div>
                                        <div class="row row-cols-1 row-cols-md-3 mb-4">
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">HTML</div></div>
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">CSS</div></div>
                                            <div class="col"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">JavaScript</div></div>
                                        </div>
                                        <div class="row row-cols-1 row-cols-md-3">
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">Ruby on Rails</div></div>
                                            <div class="col mb-4 mb-md-0"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">Ruby</div></div>
                                            <div class="col"><div class="d-flex align-items-center bg-light rounded-4 p-3 h-100">Node.js</div></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </section>
                    </div>
                </div>
            </div>
        </main>